name: ExportData

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
      - '!data/schemas/**'
      - '!data/fighters.json'
      - '!data/abilities.json'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      deployments: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: cd /home/runner/work/warcry_data/
      run: |
        cd /home/runner/work/warcry_data/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: exporting data
      run: |
        python ./python/export_data.py
    - name: commit docs
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update docs/*
        file_pattern: 'docs/**/*.json'
