name: Validation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Move to repo dir
      run: |
        cd /home/runner/work/warcry_data/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Validating fighters json
      run: |
        python ./python/validation.py
    - name: Validating abilities json
      run: >
        python ./python/validation.py 
        --data /home/runner/work/warcry_data/warcry_data/data/abilities.json 
        --schema /home/runner/work/warcry_data/warcry_data/data/schemas/aggregate_fighter_schema.json
