name: Validation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Move to repo dir
      run: |
        cd /home/runner/work/warcry_data/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.py
    - name: Validating json
      run: |
        python ./python/validation.py
